import localFont from "next/font/local";
import "../globals.css";

import Header from "@/components/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChartLine, faFileLines, faRightFromBracket } from "@fortawesome/free-solid-svg-icons";
import LogoutButton from "@/components/buttons/LogoutButton";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions)

  if (!session) {
    return redirect('/')
  }




  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <main className="flex min-h-screen">
          <aside className="bg-blue-100 w-48 p-4 ">
            <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
              <Image src={session.user.image} width={256} height={256} alt={'avater'} />
            </div>
            <div className="text-center">
              <nav className="inline-flex mx-auto flex-col text-center mt-12 gap-6 text-gray-700">
                <Link href={'/account'} className="flex gap-4  ">

                  <FontAwesomeIcon
                    fixedWidth={true}
                    icon={faFileLines}
                    className={'w-6 h-6'} />
                  <span >My Page</span>

                </Link>
                <Link href={'/analytics'} className="flex gap-4
                3.
                
                  ">
                  <FontAwesomeIcon icon={faChartLine} className={'w-6 h-6'} />
                  <span >Analytics</span>
                </Link>



                <LogoutButton iconClasses={'w-6 h-6'} iconLeft={true} classname={'flex gap-4 items-center text-gray-700'} />
              </nav>
            </div>

          </aside>
          <div className="p-6 max-w-4xl mx-auto">
            {children}

          </div>
        </main>
      </body>
    </html>
  );
}
