import localFont from "next/font/local";
import { Lato } from 'next/font/google'
import "../globals.css";

import Header from "@/components/Header";

// const geistSans = localFont({
//   src: "../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });



const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={lato.className}
      >

        <main>
          <Header />
          <div className="p-6 max-w-4xl mx-auto">
            {children}

          </div>
        </main>
      </body>
    </html >
  );
}
